---
  - name: server install
    become: true
    hosts: '{{ hosts }}'

    roles:
    - roles/server-install
    - role: frzk.chrony
      vars:
        chrony_service_name: chronyd
        chrony_ntp_pools: []
        chrony_ntp_servers:
          - 0.rhel.pool.ntp.org iburst maxpoll 10
          - 1.rhel.pool.ntp.org iburst maxpoll 10
          - 2.rhel.pool.ntp.org iburst maxpoll 10
          - 3.rhel.pool.ntp.org iburst maxpoll 10
        chrony_config_file: /etc/chrony.conf
        chrony_config_driftfile: /var/lib/chrony/drift
        chrony_config_logdir: /var/log/chrony
        chrony_makestep_threshold: 5
        chrony_makestep_limit: 3

    tasks:

    - name: timezone
      community.general.timezone:
        name: '{{ timezone }}'
      become: true

  - name: include sshd play
    ansible.builtin.import_playbook: sshd.yml

  - name: include ufw play
    ansible.builtin.import_playbook: ufw.yml

  - name: include docker install play
    ansible.builtin.import_playbook: docker-install.yml

  - name: grafana loki docker install
    become: true
    hosts: '{{ hosts }}'
    vars:
      grafana_web_port: '3000'

    roles:
    - roles/grafana-docker-install

    tasks:

    - name: Allow web port monitoring
      community.general.ufw:
        rule: allow
        route: yes
        src: "{{ nginx_proxy }}"
        port: "{{ item }}"
        proto: tcp
        comment: allow web port monitoring
      loop: 
        - "{{ grafana_web_port }}"
      when: ansible_facts['os_family'] == "Debian" and ansible_facts['distribution'] == "Ubuntu"
